# Generated by Django 3.0.3 on 2020-04-09 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('campaign_id', models.TextField()),
                ('auto_fb_post_mode', models.TextField()),
                ('current_amount', models.IntegerField()),
                ('goal', models.TextField()),
                ('donators', models.TextField()),
                ('days_active', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('has_beneficiary', models.TextField()),
                ('user_first_name', models.TextField()),
                ('user_last_name', models.TextField()),
                ('currencyCode', models.TextField()),
                ('visible_in_search', models.TextField()),
                ('campaign_hearts', models.TextField()),
                ('social_share_total', models.TextField()),
                ('DescriptionLength', models.IntegerField()),
                ('time_of_day', models.DateTimeField()),
                ('is_charity', models.TextField()),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Weekday')),
            ],
        ),
    ]
